"""initial migration

Revision ID: cf137711271d
Revises: 
Create Date: 2024-09-20 20:31:22.953998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf137711271d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=False),
    sa.Column('company_ID', sa.Integer(), nullable=False),
    sa.Column('division_ID', sa.Integer(), nullable=False),
    sa.Column('status_ID', sa.Integer(), nullable=False),
    sa.Column('fechadecreacion', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=False),
    sa.Column('is_segura_user', sa.Boolean(create_constraint=10), nullable=False),
    sa.PrimaryKeyConstraint('user_ID')
    )
    op.create_index(op.f('ix_users_mail'), 'users', ['mail'], unique=True)
    op.create_index(op.f('ix_users_user_ID'), 'users', ['user_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_ID'), table_name='users')
    op.drop_index(op.f('ix_users_mail'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
